name: Python Quality PR Check

on:
  pull_request:
    branches:
      - main
      - develop

jobs:     
  Quality-Checks-Python:
    runs-on: ubuntu-latest
    env:
      PYTHONPATH: .
    defaults:
      run:
        working-directory: python
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: gitleaks
        uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
      - name: Check PR branch
        id: check
        run: |
          if [[ ! "${GITHUB_HEAD_REF}" =~ ^(feature|hotfix|bugfix)/ ]]; then
            echo "Branch ${GITHUB_HEAD_REF} is not allowed. Failing pipeline."
            exit 1
          fi

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.11'

      - name: Install Python dependencies
        run: pip install -r requirements.txt


      - name: Run Lints and Code formatting
        uses: astral-sh/ruff-action@v3.5.1
        with:
          args: check .
          src: .

     
      - name: Running unit test cases and Code Coverage
        run: |
             python -m unittest 
             coverage run -m unittest
             coverage report -m



      - name: Build and Compile Code
        run: python -m compileall .
